### ISSUE TITLE
I think there's a error in \dokan\__init__.py[line 491]

### ISSUE THREAD

**Issue by chenjt2001** [nznaza/pyfilesystem_dokan#1]
\dokan\__init__.py[line 491]
DokanFileInfo.contents.IsDirectory = 1
should be changed to
DokanFileInfo.contents.IsDirectory = 0

If use 'DokanFileInfo.contents.IsDirectory = 1', the file cannot be deleted.It will appear when use F5 .
Use "DokanFileInfo.contents.IsDirectory = 0" can solve the problem.

In addition, in order to adapt to the latest version of dokan,  \dokan\libdokan.py[line 34]“DOKAN_MINIMUM_COMPATIBLE_VERSION = 100” should be changed to 110.

Do you think?
[sorry.I am not good at English.

**Comment by nznaza** [comment]
The version check is fixed in the a new branch.
Will look into the rest of fixes

**Comment by nznaza** [comment]
Thanks for your input, indeed and as noted by the coments right above that line it should have been DokanFileInfo.contents.IsDirectory = 0 instead of = 1.
This is fixed in the last commit
