### ISSUE TITLE
testdokan.py example fails

### ISSUE THREAD

**Issue by tstreibl** [nznaza/pyfilesystem_dokan#3]
Hi,

when I run the testdokan.py example I get "OSError: Dokan failed with error: -7". The error number corresponds to the DOKAN_VERSION_ERROR, meaning "Dokan mount failed. Requested an incompatible version."

I installed the latest version of the dokan driver V1.3.1.1000 from https://github.com/dokan-dev/dokany/releases. What's my mistake?

**Comment by nznaza** [comment]
Please clone the branch dokan-V1.3.1

**Comment by tstreibl** [comment]
Great - got it running! Only a small hint on something you might already know:

When I mount with "foreground=True" I get Q-Drive attached, but python interpreter stops in this line. (I used spyder with winpython distribution) 

When I mount with "foreground=False" I get an error in dokan\__init__.py", line 1128, in __init__
    cmd = cmd % (repr(pickle.dumps((fs, path, dokan_opts, nowait), -1)),)
TypeError: can't pickle _thread.RLock objects

**Comment by nznaza** [comment]
@tstreibl yes, it was in the TODO in the readme, pull the new changes there is a new example, please don hesitate to ping me any errors in the module you found.
